name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
    - name: Update Dependencies
      run: composer update  --ignore-platform-req=php+
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Clear config
      run: php artisan config:clear
    - name: Clear cache
      run: php artisan cache:clear
    # - name: Execute tests (Unit and Feature tests) via PHPUnit
    #   env:
    #     DB_CONNECTION: mysql
    #     DB_HOST: coverage_db
    #     DB_PORT: 3306
    #     DB_DATABASE: coverage
    #     DB_USERNAME: root
    #     DB_PASSWORD: huypq29102001
    #   run: vendor/bin/phpunit --testdox
    - name: Optimize artisan
      run: php artisan optimize
